# Generated by Django 3.2.16 on 2022-10-07 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_is_fixer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_fixer',
        ),
    ]
