# Generated by Django 3.2.16 on 2022-10-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_task_is_fixer'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_fixed',
            field=models.BooleanField(default=False, verbose_name='Fixed'),
        ),
    ]
